blog/urls.py
from django.conf.urls import url,include
from .import views


app_name='blog'
'''
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
]
'''
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
   # url(r'^search/$',views.search,name='search'),

]

blogproject2/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
    url(r'^all/rss/$',AllPostsRssFeed(),name='rss'),
    url(r'^search/$',include('haystack.urls')),
]

comments/models.py
#!-*-coding:utf-8-*-
from django.db import models
from django.utils.six import python_2_unicode_compatible
from blog.models import Post
# Create your models here.
@python_2_unicode_compatible
class Comment(models.Model):
    #保存评论用户的 name（名字）、email（邮箱）、url（个人网站），用户发表的内容将存放在 text 字段里，created_time 
    #记录评论时间。最后，这个评论是关联到某篇文章（Post）的，由于一个评论只能属于一篇文章，一篇文章可以有多个评论， 
    #是一对多的关系，因此这里我们使用了 ForeignKey
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    #DateTimeField 传递了一个 auto_now_add=True 的参数值。auto_now_add 的作用是，当评论数据保存到数据库时,
    #自动把 created_time的值指定为当前时间。created_time 记录用户发表评论的时间
    created_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post')
    def __str__(self):
        return self.text[:20]
    class Meta:
        ordering = ["-created_time"]

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}
<!--
{% load blog_tags %}
-->
{% block main %}
    {% if query %}
    {% for result in page.object_list %}
         <article class="post post--{{ result.object.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">
                            <a href="{{ result.object.get_absolute_url }}">{% highlight result.object.title with query %}</a>
                        </h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="{% url 'blog:category' result.object.category.pk %}">{{ result.object.category.name }}</a></span>
                            <span class="post-date"><a href="#"><time class="entry-date"
                                                                      datetime="{{ result.object.created_time }}">{{ result.object.created_time }}</time></a></span>
                            <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                            <span class="comments-link"><a href="{{ result.object.get_absolute_url }}">{{ result.object.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="{{ result.object.get_absolute_url }} ">{{ result.object.views }}阅读</a></span>
                        </div>
                    </header>
                    <div class="entry-content clearfix">
                        <p>{% highlight result.object.body with query %} ...</p>
                        <div class="read-more cl-effect-14">
                            <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                        </div>
                    </div>
        </article>
        {% empty %}
             <div class="no-post"><strong>没有搜索到你想要的结果！</strong></div>
        {% endfor %}                

        {% if page.has_previous or page.has_next %}
                <div >
                   
                    {% if page.has_previous %}
                    <a href="?q={{ query }}&amp; page={{ page.previouse_page_number }}">{% endif %}&laquo; 上一页{% if page.has_previous %}</a>{% endif %}
                   
                    
                    {% if page.has_next %}
                    <a href="?={{ query }}&amp; page={{ page.next_page_number }}">{% endif %}下一页&raquo;{% if page.has_next %}</a>{% endif %}

                </div>
        {% endif %}
    {% else %}
        请输入关键词，例如django
    {% endif %}
           

{% endblock main %}
                